---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: joplin-server
  labels:
    app: joplin-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: joplin-server
  template:
    metadata:
      labels:
        app: joplin-server
    spec:
      containers:
      - name: joplin-server
        image: joplin/server:2.4.1-beta
        env:
        - name: APP_BASE_URL
          value: "https://your.hostname.com/"
        - name: APP_PORT
          value: "22300"
        - name: USER_CONTENT_BASE_URL
          value: ""
        - name: API_BASE_URL
          value: "api"
        - name: SQLITE_DATABASE
          value: "true"
        - name: POSTGRES_HOST
          value: ""
        - name: POSTGRES_PORT
          value: ""
        - name: POSTGRES_PASSWORD
          value: ""
        - name: POSTGRES_DATABASE
          value: ""
        - name: SIGNUP_ENABLED
          value: "false"
        - name: TERMS_ENABLED
          value: "false"
        - name: ERROR_STACK_TRACES
          value: "true"
        - name: SUPPORT_EMAIL
          value: ""
        - name: SUPPORT_NAME
          value: ""
        - name: COOKIES_SECURE
          value: ""
        ports:
        - containerPort: 22300
